// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajlChh099mZ6QNFusYItufb_X_TByokw',
    appId: '1:903175298103:web:ef7c37c08e6117de83f3b2',
    messagingSenderId: '903175298103',
    projectId: 'moc-erahspans',
    authDomain: 'moc-erahspans.firebaseapp.com',
    storageBucket: 'moc-erahspans.firebasestorage.app',
    measurementId: 'G-WZLWX40M0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCScrZQi4lIjK0HjUg-h6z4eRsB4nqlqQw',
    appId: '1:903175298103:android:19356d935b78741983f3b2',
    messagingSenderId: '903175298103',
    projectId: 'moc-erahspans',
    storageBucket: 'moc-erahspans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9tIy-ZlxzPFr6oL4cbz0Y7E49a4Gmtw',
    appId: '1:903175298103:ios:4fc8f905161a9e7f83f3b2',
    messagingSenderId: '903175298103',
    projectId: 'moc-erahspans',
    storageBucket: 'moc-erahspans.firebasestorage.app',
    iosClientId: '903175298103-po6nun2jjkcp99jl64vrncom692r8c42.apps.googleusercontent.com',
    iosBundleId: 'erahspans.moc.snapshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9tIy-ZlxzPFr6oL4cbz0Y7E49a4Gmtw',
    appId: '1:903175298103:ios:4fc8f905161a9e7f83f3b2',
    messagingSenderId: '903175298103',
    projectId: 'moc-erahspans',
    storageBucket: 'moc-erahspans.firebasestorage.app',
    iosClientId: '903175298103-po6nun2jjkcp99jl64vrncom692r8c42.apps.googleusercontent.com',
    iosBundleId: 'erahspans.moc.snapshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAajlChh099mZ6QNFusYItufb_X_TByokw',
    appId: '1:903175298103:web:930c4fb3d45ca63f83f3b2',
    messagingSenderId: '903175298103',
    projectId: 'moc-erahspans',
    authDomain: 'moc-erahspans.firebaseapp.com',
    storageBucket: 'moc-erahspans.firebasestorage.app',
    measurementId: 'G-5WZ29H8L85',
  );
}
